### ISSUE TITLE
Failed at the foie-graphs start script

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-stats#2]
Upstream issue: https://github.com/wombleton/foie-graphs/issues/3

```
imamopravoznati-stats % USER=schlos REPO=foie-graphs TOKEN=OAUTH_GUTHUB_token ALAVETELI=http://imamopravoznati.org npm start

> foie-graphs@0.0.2 start /Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats
> node index.js
...
...
...
fs.js:143
  throw new ERR_INVALID_CALLBACK(cb);
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:143:9)
    at Object.writeFile (fs.js:1267:14)
    at Scraper.<anonymous> (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/index.js:38:8)
    at Scraper.emit (events.js:321:20)
    at Scraper.<anonymous> (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/lib/scraper.js:18:18)
    at next (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/async/lib/async.js:726:31)
    at /Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/async/lib/async.js:24:16
    at Timeout._onTimeout (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/underscore/underscore.js:620:47)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ERR_INVALID_CALLBACK'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foie-graphs@0.0.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foie-graphs@0.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miroslav/.npm/_logs/2020-12-20T08_26_00_030Z-debug.log
```

Debug log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v13.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foie-graphs@0.0.2~prestart: foie-graphs@0.0.2
6 info lifecycle foie-graphs@0.0.2~start: foie-graphs@0.0.2
7 verbose lifecycle foie-graphs@0.0.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle foie-graphs@0.0.2~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Keybase.app/Contents/SharedSupport/bin
9 verbose lifecycle foie-graphs@0.0.2~start: CWD: /Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats
10 silly lifecycle foie-graphs@0.0.2~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle foie-graphs@0.0.2~start: Returned: code: 1  signal: null
12 info lifecycle foie-graphs@0.0.2~start: Failed to exec start script
13 verbose stack Error: foie-graphs@0.0.2 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid foie-graphs@0.0.2
15 verbose cwd /Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/Cellar/node/13.6.0/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v13.6.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error foie-graphs@0.0.2 start: `node index.js`
22 error Exit status 1
23 error Failed at the foie-graphs@0.0.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
/Users/miroslav/.npm/_logs/2020-12-20T08_26_00_030Z-debug.log (END)
```

**Comment by schlos** [comment]
Investigation:

> index.js
> fs.js:
>   throw new ERR_INVALID_CALLBACK(cb);

https://stackoverflow.com/questions/50438592/typeerror-err-invalid-callback-callback-must-be-a-function

Issue could be as described on StackOverflow at line: https://github.com/codeforcroatia/imamopravoznati-stats/blob/master/index.js#L38

**Comment by schlos** [comment]
NodeJS documentation: https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback

**Comment by schlos** [comment]
Fixed (locally, not yet pushed)

**Comment by schlos** [comment]
Same issue with process.js:

```
imamopravoznati-stats % npm start      

> foie-graphs@0.0.2 start /Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats
> node process.js

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Tue Jan 01 2019 00:00:00 GMT+0100 (Central European Standard Time), _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/moment/moment.js:320:98)
    at configFromString (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/moment/moment.js:2385:15)
    at configFromInput (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/moment/moment.js:2611:13)
    at prepareConfig (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/moment/moment.js:2594:13)
    at createFromConfig (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/moment/moment.js:2561:44)
    at createLocalOrUTC (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/moment/moment.js:2648:16)
    at createLocal (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/moment/moment.js:2652:16)
    at hooks (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/node_modules/moment/moment.js:12:29)
    at Store.getOptions (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/lib/store.js:77:15)
    at Object.<anonymous> (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/process.js:18:53)
fs.js:143
  throw new ERR_INVALID_CALLBACK(cb);
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:143:9)
    at Object.writeFile (fs.js:1267:14)
    at Object.<anonymous> (/Users/miroslav/CodeForCroatia/Workspace CFC/imamopravoznati-stats/process.js:18:4)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_CALLBACK'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foie-graphs@0.0.2 start: `node process.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foie-graphs@0.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miroslav/.npm/_logs/2020-12-20T10_33_13_572Z-debug.log
```
